"""Cambiamento chiave primaria di 'Insegnamenti'. Passata da int a string

Revision ID: 29aa1297544a
Revises: 
Create Date: 2023-05-08 17:20:57.031905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29aa1297544a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insegnamenti', schema=None) as batch_op:
        batch_op.alter_column('codice',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insegnamenti', schema=None) as batch_op:
        batch_op.alter_column('codice',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
