"""Added the Ruolo Enum for teachers role

Revision ID: 30743c1e408e
Revises: 60439358f0c7
Create Date: 2023-05-09 15:44:36.704706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30743c1e408e'
down_revision = '60439358f0c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_docenti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruolo', sa.Enum('presidente', 'membro', name='ruolo'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_docenti', schema=None) as batch_op:
        batch_op.drop_column('ruolo')

    # ### end Alembic commands ###
