"""Prova 1

Revision ID: 74fbed30750a
Revises: 
Create Date: 2023-05-19 17:20:43.613302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fbed30750a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corsi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'insegnamenti', ['codice_insegnamento'], ['codice'], initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('esami', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'corsi', ['codice_corso'], ['codice'], initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('esami_svolti', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'studenti', ['matricola_studente'], ['matricola'], initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key(None, 'esami', ['id_esame'], ['id'], initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('lista_docenti', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'docenti', ['id_docente'], ['id'], initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key(None, 'esami', ['id_esame'], ['id'], initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('lista_iscritti', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'studenti', ['matricola_studente'], ['matricola'], initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key(None, 'prove', ['id_prova'], ['id'], initially='DEFERRED', deferrable=True)

    with op.batch_alter_table('prove', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'docenti', ['id_docente'], ['id'], initially='DEFERRED', deferrable=True)
        batch_op.create_foreign_key(None, 'esami', ['id_esame'], ['id'], initially='DEFERRED', deferrable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prove', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'docenti', ['id_docente'], ['id'])
        batch_op.create_foreign_key(None, 'esami', ['id_esame'], ['id'])

    with op.batch_alter_table('lista_iscritti', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'studenti', ['matricola_studente'], ['matricola'])
        batch_op.create_foreign_key(None, 'prove', ['id_prova'], ['id'])

    with op.batch_alter_table('lista_docenti', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'docenti', ['id_docente'], ['id'])
        batch_op.create_foreign_key(None, 'esami', ['id_esame'], ['id'])

    with op.batch_alter_table('esami_svolti', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'studenti', ['matricola_studente'], ['matricola'])
        batch_op.create_foreign_key(None, 'esami', ['id_esame'], ['id'])

    with op.batch_alter_table('esami', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'corsi', ['codice_corso'], ['codice'])

    with op.batch_alter_table('corsi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'insegnamenti', ['codice_insegnamento'], ['codice'])

    # ### end Alembic commands ###
